package com.byebye.chapterTwo.global.auth.exception

class CustomException (

    val customErrorCode: CustomErrorCode

) : RuntimeException ()
